apiVersion: v1
kind: Service
metadata:
  name: spring-webservice-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    type: web-service
