# Create Service 
#run -> kubectl create -f node-port-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: node-port-service

spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30008 # port for external access. 
      targetPort: 80 # pod port 
  selector: 
    # below labels are from pod defination.
    # this link service to the pods.   
    app: nginx


# test https://172.17.0.15:30008