apiVersion: v1
kind: Pod
metadata:
  name: simple-web-app
  namespace: web-app
  labels:
    app: web-app

spec:
  nodeSelector:
    disktype: ssd ## node lable 
    
  tolerations:
      - key: "spray" 
        effect: "NoSchedule"
        value: "mortein"
        operator: "Equal"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists

  volumes:
    - name: data-volume # name to be used along with 
      hostPath:
          path: /data
          type: Directory

  containers:
    - name: simple-web-app
      image: simple-web-app
      
      command:  ## Sample Command 
        - "ls"
      args:
        - "-a" ## Sample Arguments

      ports:
        - containerPort: 8080
          protocol: TCP

      readinessProbe: #  readiness prob with httpGet
        httpGet:
          port: 8080
          path: /api/ready
        
        initialDelaySeconds: 10 # Number of seconds after the container has started before liveness probes are initiated.
        periodSeconds: 1         # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
        failureThreshold: 0     # Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.

      livenessProbe:
        httpGet:
          port: 8080
          path: /api/ready
        initialDelaySeconds: 10
        periodSeconds: 1
        failureThreshold: 0 

      env:
        - name: DB_Host
          valueFrom:
            secretKeyRef:
              key: DB_Host
              name: db-secret
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              key: DB_Password
              name: db-secret
        - name: DB_User
          valueFrom:
            secretKeyRef:
              key: DB_User
              name: db-secret

      volumeMounts:
        - mountPath: /opt
          name: data-volume
