apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    type: front-end ## this label is given as selector  
    enviroment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80