apiVersion: v1
kind: Pod
metadata:
  name : simple-web-app
spec:
  containers:
    - name: simple-web-app
      image: simple-web-app
      ports:
        - containerPort: 8080
      readinessProbe: #  readiness prob with httpGet
        httpGet:
          port: 8080
          path: /api/ready
        # Number of seconds after the container has started before liveness probes are initiated. 
        initialDelaySeconds: 10
        # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
        periodSeconds: 1
        # Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
        failureThreshold: 0 
      livenessProbe:
        httpGet:
          port: 8080
          path: /api/ready
        # Number of seconds after the container has started before liveness probes are initiated. 
        initialDelaySeconds: 10
        # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
        periodSeconds: 1
        # Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
        failureThreshold: 0 
          
      

           

             
              