apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend

spec:
  replicas: 3
  template:
    metadata:
      name: httpd-frontend
      labels:
        type: httpd-frontend
    spec:
      containers:
        - name: httpd-frontend
          image: httpd:2.4-alpine
  selector:
    matchLabels:
      type: httpd-frontend