apiVersion: batch/v1 
kind: Job
metadata:
  name: maths-add-job
spec:
  template:
    spec:
      containers:
        - name: maths-pod
          image: ubuntu
          command: ['expr','3','+','2']
      restartPolicy: Never
        