## run simple-web-app-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-color-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    type: simple-webapp-color
   