apiVersion: v1
kind: Service
metadata:
  name: sql01
  labels:
    name: mysql-pod
    app: demo-app
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
   