apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    app: demo-app
spec:
  containers:
  - name: mysql
    image: mysql:5.6  
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password123
    ports:
      - containerPort: 3306
        protocol: TCP