# this specification shows how to use inject secrets via volumes. 
# run kubectl create -f nginx-secret-as-volume.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
    - name: nginx-vol
      secret:
          secretName: db-secret
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /opt/secret/
          name: nginx-vol
          readOnly: true
      
