### run --> kubectl create -f simple-secret.yaml

#
#Secret Name: db-secret
#Secret 1: DB_Host=sql01  | base64 = c3FsMDE=
#Secret 2: DB_User=root | cm9vdA==
#Secret 3: DB_Password=password123 | cGFzc3dvcmQxMjM=
#

apiVersion: v1
data:
  DB_Host: c3FsMDE=
  DB_Password: cGFzc3dvcmQxMjM=
  DB_User: cm9vdA==
kind: Secret
metadata:
  name: db-secret