# this specification is to create sevice for  simple-webapp-mysql
# run kubectl create -f simple-webapp-mysql-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-mysql-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    type: simple-webapp-mysql
   