apiVersion: v1 
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
    - name: ubuntu 
      image: ubuntu
      command:
        - "sleep"
        - "4800"
      securityContext: # this will be applied at container level 
          runAsUser: 1000
          capabilities: ## capabilities supported only at Container level not at pod level.
            add:
              - "MAC_ADMIN"