apiVersion: v1 
kind: Pod
metadata:
  name: bee
spec:
  containers:
    - name: bee
      image: nginx
  tolerations:
    - key: "spray" 
      effect: "NoSchedule"
      value: "mortein"
      operator: "Equal"

        

