#run -> kubectl create -f Replication-Controller.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod

spec:
  replicas: 2 # number of replicas
  template:
    ## Pod Defination starts from here 
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: test-container
        image: nginx

