#run -> kubectl create -f first-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: front-end
    tier: fornt-end
    enviroment: dev 
spec:
  containers:
    - name: nginx-containers
      image: nginx
