apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: front-end
    tier: fornt-end
    developedBy: Sumit Gupta
    enviroment: dev 
spec:
  containers:
    - name: nginx-containers
      image: nginx
